### ISSUE TITLE
Tests don't work on views since v3.0.2

### ISSUE THREAD

**Issue by hlepouse-vasco** [dataform-co/dataform#1851]
No issue in v3.0.0
When switching to v3.0.2, all tests on views don't work anymore (compilation error).
<img width="230" alt="image" src="https://github.com/user-attachments/assets/43288e42-6bf2-4562-ba15-935450c21ff6">
<img width="318" alt="image" src="https://github.com/user-attachments/assets/2c77bfe3-1664-4e6e-aa4e-9057b6f12537">

<img width="741" alt="image" src="https://github.com/user-attachments/assets/c498de39-df87-4e92-89c3-c3fd31104fd9">

When changing type from "view" to "table", it works fine.

**Comment by hlepouse-vasco** [comment]
just found out it's already fixed in main https://github.com/dataform-co/dataform/pull/1824
waiting for next release then
