### ISSUE TITLE
explicit variable assignment when using javascript function causing error

### ISSUE THREAD

**Issue by ashish10alex** [dataform-co/dataform#1940]
### Issue description 
When using javascript function that supports variables as input if we explicitly assign variables when calling the function it is causes a compilation error when using Dataform cli.  Note that this compilation errors does not occur in Dataform GCP UI. Please see the simplest reproducible example.

```sql
config {
  type: 'view'
}

js {
  function someOperation(var1){
   return `"${var1}"`
}

}

select 
-- ${someOperation('hello')} as some_column           -- works
    ${someOperation(var1='hello') } as some_column   -- does not work
```

### Environment

Dataform version: Does not work in both v2.9 and v3.0.16
Node version: v22.13.0
Operating system: Windows & Mac OS

![Image](https://github.com/user-attachments/assets/1e681e92-c17d-4b7e-a513-1a0c034fb78e)

### Related issues

https://github.com/ashish10alex/vscode-dataform-tools/issues/124

**Comment by benjaminwestern** [comment]
Additional context:
# Named Parameters in JavaScript Functions

## Issue Summary
Dataform CLI fails to compile when JavaScript functions are called with named parameters, but works correctly with positional parameters. This is a CLI parsing bug, not a VS Code extension issue.

## Environment
- Dataform CLI version: 3.0.26
- Platform: macOS (also reported on WSL2/Ubuntu-24.04)

## Reproduction Steps

### 1. Create a new Dataform project
```bash
mkdir dataform-test && cd dataform-test
dataform init . test-project us-central1
```

### 2. Create helper function
Create `includes/helper.js`:
```javascript
function create_financeads_key_for_reports(affiliate_id, country) {
   return `
   trim(array_to_string(
       [
           safe_cast(${affiliate_id} as string)
           ,${country}
       ]
       , '-', 'null'
   ))
   `
}

module.exports = {
  create_financeads_key_for_reports
};
```

### 3. Test Case 1: Named Parameters (FAILS)
Create `definitions/test_named_params.sqlx`:
```sql
config {
  type: 'view'
}

js {
  const helper = require("../includes/helper");
}

select 
  'test' as affiliate_name,
  123 as affiliate_id,
  'US' as country,
  ${helper.create_financeads_key_for_reports(
    affiliate_id = "123",
    country = "'US'"
  )} as financeads_key_with_named_params
```

### 4. Test Case 2: Positional Parameters (WORKS)
Create `definitions/test_positional_params.sqlx`:
```sql
config {
  type: 'view'
}

js {
  const helper = require("../includes/helper");
}

select 
  'test' as affiliate_name,
  123 as affiliate_id,
  'US' as country,
  ${helper.create_financeads_key_for_reports("123", "'US'")} as financeads_key_positional
```

### 5. Run Compilation Test
```bash
dataform compile --timeout 60000
```

## Results

### ❌ Named Parameters Result
```
Compilation errors:
definitions/test_named_params.sqlx: ReferenceError: affiliate_id is not defined
    at Object.sqlContextable (/tmp/definitions/test_named_params.sqlx:33:18)
```

### ✅ Positional Parameters Result
```
Compiled 1 action(s).
1 dataset(s):
  dataform.test_positional_params [view]
```

## Root Cause Analysis

The Dataform CLI incorrectly parses named parameter syntax:
- `affiliate_id = "123"` is treated as a variable reference to `affiliate_id`
- Instead of being parsed as a named parameter assignment

## Workaround

**Replace named parameters:**
```javascript
// ❌ This fails
${helper.someFunction(param1='value1', param2='value2')}

// ✅ Use this instead  
${helper.someFunction('value1', 'value2')}
```
