### ISSUE TITLE
Can't require absolute paths on latest (unreleased) version of Dataform

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#1325]
This is appearing since the recent upgrades to `vm2`

Before you could do something like:

```
select ${require("/definitions/test.json").a} as test
```

This compiles fine on version 1.21.1

With the latest code, this will fail:

```
VMError: Cannot find module '/definitions/test.json'
```

Relative require calls, like: 

```
select ${require("./test.json").a} as test
```

Work fine on the latest version.

**Comment by lewish** [comment]
I'm not sure this was actually ever intended to be supported, but it did previously work nonetheless.

Removing the trailing slash on absolute imports should work, and is how the functionality is documented: https://docs.dataform.co/guides/javascript/js-api#nested-includes

```
select ${require("definitions/test.json").a} as test
```

**Comment by BenBirt** [comment]
Closing per above (this wasn't ever supposed to work - please don't use a leading slash).
