### ISSUE TITLE
1.22.0 won't run

### ISSUE THREAD

**Issue by pwm1991** [dataform-co/dataform#1348]
When upgrading to 1.22.0, dataform will no longer initialise. The following errors are given.

```
Compilation errors: Error
[Environment errors](https://app.dataform.co/#/6327098152058880/b/WTF/file/environments.json):
--
Error
--
Could not retrieve the [environments.json](https://app.dataform.co/#/6327098152058880/b/WTF/file/environments.json) file on the production branch. [Check](https://app.dataform.co/#/usersettings) that your your personal Git access token is valid for the remote repository this project is attached to. Error message:
--
Schedule error: Error: Error: 1 CANCELLED: Command failed: npm ci --ignore-scripts --only=production%0Anpm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.%0Anpm ERR! %0Anpm ERR! %0Anpm ERR! Invalid: lock file's @dataform/core@1.21.1 does not satisfy @dataform/core@^1.22.0%0Anpm ERR! Missing: dayjs@^1.11.3%0Anpm ERR! %0A%0Anpm ERR! A complete log of this run can be found in:%0Anpm ERR! /mounts/npm-cache-root/npm/_logs/2022-06-10T08_23_45_204Z-debug.log%0A
---
Schedule error: Error
---
Could not retrieve the [environments.json](https://app.dataform.co/#/6327098152058880/b/WTF/file/environments.json) file on the production branch. [Check](https://app.dataform.co/#/usersettings) that your your personal Git access token is valid for the remote repository this project is attached to. Error message:
```

Dataform compiles fine using Node v17.8.0 / NPM 8.7.0 locally.

===

Project: `6327098152058880`
Package:
```{
    "dependencies": {
        "@dataform/core": "1.22.0",
        "@tilburytech/ct-dataform": "^1.3.0",
        "@tilburytech/ct-snowplow-schema-metadata": "latest",
        "ajv": "^8.6.0",
        "dayjs": "^1.11.3"
    },
    "scripts": {
        "test": "jest",
        "test:watch": "jest --watch",
        "lint": "eslint includes/ build/ --ext .js",
        "lint:fix": "eslint includes/ build/ --ext .js  --fix",
        "release": "node build/release.js",
        "dataform": "dataform compile --watch"
    },
    "devDependencies": {
        "eslint": "^7.24.0",
        "jest": "^27.5.1",
        "lint-staged": "^10.5.4"
    },
    "lint-staged": {
        "*.js": "eslint --cache --fix"
    }
}
```

**Comment by G2H** [comment]
Hi - this question seems related to the Dataform application. Please ask the question via the intercom messenger at the bottom right of the app. Our support team will be able to help with the specifics of your project.
