### ISSUE TITLE
Bug: `publish` function stopped working in folder `includes/` which breaks udf unit-testing

### ISSUE THREAD

**Issue by mokshasoul** [dataform-co/dataform#1908]
Hello everyone,

We have an adapted [version of this](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/tests/dataform_testing_framework/includes/unit_test_utils.js)

Behavior:

```text
TypeError: publish(...).type is not a function
```

This started happening with version dataform version `3.0.10`.

This functionality was essential and the library lives in `includes/`.

**Comment by Ekrekr** [comment]
Hi Charis-Nicolas,

Thanks for the heads up. I expect a bug was introduced in https://github.com/dataform-co/dataform/pull/1780 that is causing this. We'll patch a fix for it in the next few days - for now just stick with 3.0.9.

Thanks,
Elias

**Comment by mokshasoul** [comment]
Hi @Ekrekr thx for the quick update
